# Generated by Django 5.2.8 on 2025-11-18 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cours_images/')),
                ('est_publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_cours', to='xcsm.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='FichierSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('fichier_original', models.FileField(upload_to='documents_bruts/', verbose_name='PDF Original')),
                ('mongo_transforme_id', models.CharField(blank=True, help_text="ID du document transformé (HTML/XML) dans la collection MongoDB 'Fichiers Uploades'", max_length=100, null=True)),
                ('statut_traitement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITE', 'Traité'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=20)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_fichiers', to='xcsm.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='xcsm.cours')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='xcsm.partie')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='xcsm.chapitre')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='SousSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_sections', to='xcsm.section')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Granule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type_contenu', models.CharField(default='TEXTE', max_length=50)),
                ('mongo_contenu_id', models.CharField(help_text='ID du fragment dans MongoDB', max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('fichier_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granules_extraits', to='xcsm.fichiersource')),
                ('sous_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granules', to='xcsm.soussection')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
