# Generated by Django 5.2.8 on 2026-01-14 10:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0002_cours_fichiersource_partie_chapitre_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('difficulte', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyen'), (3, 'Difficile')], default=1)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercices_globaux', to='xcsm.cours')),
                ('granule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercices', to='xcsm.granule')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enonce', models.TextField()),
                ('type_question', models.CharField(choices=[('QCM', 'QCM'), ('VRAI_FAUX', 'Vrai/Faux'), ('TROUS', 'Texte à trous'), ('ASSOCIATION', 'Association'), ('ORDRE', 'Mise en ordre'), ('OUVERTE', 'Question Ouverte')], max_length=20)),
                ('point', models.FloatField(default=1.0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='xcsm.exercice')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texte', models.TextField()),
                ('est_correcte', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, help_text='Explication affichée après réponse')),
                ('correspondance', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='xcsm.question')),
            ],
        ),
        migrations.AddField(
            model_name='granule',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='granules', to='xcsm.tag'),
        ),
    ]
