# Generated by Django 5.2.8 on 2026-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0003_categorie_tag_exercice_question_reponse_granule_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_organisations/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
