# Generated by Django 5.2.8 on 2026-01-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0004_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='granule',
            name='source_pdf_page',
            field=models.PositiveIntegerField(blank=True, help_text='Numéro de page dans le PDF original', null=True),
        ),
    ]
