# Generated by Django 5.2.8 on 2026-01-18 10:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0005_granule_source_pdf_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='etudiants_inscrits',
            field=models.ManyToManyField(blank=True, related_name='cours_suivis', to='xcsm.etudiant', verbose_name='Étudiants inscrits'),
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_etudiants', to='xcsm.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='xcsm.etudiant')),
                ('granule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xcsm.granule')),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'unique_together': {('etudiant', 'granule')},
            },
        ),
    ]
