# Generated by Django 5.2.8 on 2026-01-23 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0006_cours_etudiants_inscrits_progression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.ImageField(upload_to='ressources/', verbose_name='Fichier Média')),
                ('type_ressource', models.CharField(default='IMAGE', max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='xcsm.cours')),
                ('fichier_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources_extraites', to='xcsm.fichiersource')),
            ],
        ),
    ]
