# Generated by Django 5.2.8 on 2026-01-26 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0007_ressource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date concernée', unique=True)),
                ('total_documents_processed', models.IntegerField(default=0)),
                ('total_documents_success', models.IntegerField(default=0)),
                ('total_documents_failed', models.IntegerField(default=0)),
                ('total_granules_created', models.IntegerField(default=0)),
                ('avg_extraction_time', models.FloatField(blank=True, help_text="Temps moyen d'extraction de texte", null=True)),
                ('avg_granulation_time', models.FloatField(blank=True, help_text='Temps moyen de génération de granules', null=True)),
                ('avg_total_time', models.FloatField(blank=True, help_text='Temps moyen total de traitement', null=True)),
                ('active_users_count', models.IntegerField(default=0, help_text="Nombre d'utilisateurs actifs ce jour")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrique de traitement',
                'verbose_name_plural': 'Métriques de traitement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code matière')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_matieres', to='xcsm.enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='xcsm.matiere'),
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('UPLOAD', 'Upload du fichier'), ('EXTRACTION_TEXT', 'Extraction de texte'), ('EXTRACTION_IMAGES', "Extraction d'images"), ('GRANULATION', 'Génération de granules'), ('OCR', 'Reconnaissance optique (OCR)'), ('INDEXING', 'Indexation vectorielle'), ('COMPLETE', 'Traitement complet')], help_text="Type d'opération effectuée", max_length=50)),
                ('status', models.CharField(choices=[('STARTED', 'Démarré'), ('IN_PROGRESS', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec'), ('RETRYING', 'Nouvelle tentative')], default='STARTED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Durée en secondes', null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='ID de la tâche Celery', max_length=255, null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Nombre de tentatives')),
                ('result_summary', models.JSONField(blank=True, help_text='Résumé des résultats (granules créés, etc.)', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Message d'erreur en cas d'échec", null=True)),
                ('error_traceback', models.TextField(blank=True, help_text="Traceback complet de l'erreur", null=True)),
                ('fichier_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='xcsm.fichiersource')),
            ],
            options={
                'verbose_name': 'Log de traitement',
                'verbose_name_plural': 'Logs de traitement',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['fichier_source', '-started_at'], name='xcsm_proces_fichier_4cf3fb_idx'), models.Index(fields=['status', '-started_at'], name='xcsm_proces_status_e8bdbc_idx'), models.Index(fields=['operation', '-started_at'], name='xcsm_proces_operati_dbc07c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('REGISTER', 'Inscription'), ('UPLOAD_FILE', 'Upload de fichier'), ('CREATE_COURSE', 'Création de cours'), ('UPDATE_COURSE', 'Modification de cours'), ('DELETE_COURSE', 'Suppression de cours'), ('ENROLL_COURSE', 'Inscription à un cours'), ('GENERATE_QCM', 'Génération de QCM'), ('SEARCH', 'Recherche'), ('VIEW_DOCUMENT', 'Consultation de document'), ('DOWNLOAD', 'Téléchargement')], max_length=100)),
                ('resource_type', models.CharField(blank=True, help_text='Type de ressource (Cours, Fichier, etc.)', max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, help_text='ID de la ressource concernée', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent du navigateur', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Données additionnelles (query de recherche, etc.)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité utilisateur",
                'verbose_name_plural': "Logs d'activité utilisateur",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='xcsm_userac_user_id_87a8f1_idx'), models.Index(fields=['action', '-timestamp'], name='xcsm_userac_action_6c0bc6_idx'), models.Index(fields=['resource_type', 'resource_id'], name='xcsm_userac_resourc_20654a_idx')],
            },
        ),
    ]
