# Generated by Django 5.2.8 on 2026-01-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0008_processingmetrics_matiere_cours_matiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='matiere',
        ),
        migrations.DeleteModel(
            name='Matiere',
        ),
    ]
