# Generated by Django 5.2.8 on 2026-01-26 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xcsm', '0009_remove_cours_matiere_delete_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='code',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='etudiants_inscrits',
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name="Code d'accès (défini par l'enseignant)")),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='matieres_images/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_matieres', to='xcsm.enseignant')),
                ('etudiants_inscrits', models.ManyToManyField(blank=True, related_name='matieres_suivies', to='xcsm.etudiant', verbose_name='Étudiants inscrits')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cours_associes', to='xcsm.matiere'),
        ),
        migrations.AddField(
            model_name='fichiersource',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='xcsm.matiere'),
        ),
    ]
